config/routes.rb
Rails.application.routes.draw do


  get 'search/search'
   devise_for :users
   root to: 'homes#top'

   get 'home/about' => 'homes#about'


  resources :books, only: [:index, :show, :edit, :create, :destroy, :update] do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  resources :users, only: [:index, :show, :edit, :update] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :body, presence: true, length: {maximum: 200}
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def self.search_for(content, method)
    if method == 'perfect'
      Book.where(title: content)
    elsif method == 'forward'
      Book.where('title LIKE ?', content+'%')
    elsif method == 'backward'
      Book.where('title LIKE ?', '%'+content)
    else
      Book.where('title LIKE ?', '%'+content+'%')
    end
  end

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :followings, through: :relationships, source: :followed

  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :name, presence: true, length: { in: 2..20 }, uniqueness: true
  validates :introduction, length: {maximum: 50}
  attachment :profile_image

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

  def self.search_for(content, method)
    if method == 'perfect'
      User.where(name: content)
    elsif method == 'forward'
      User.where('name LIKE ?', content + '%')
    elsif method == 'backward'
      User.where('name LIKE ?', '%' + content)
    else
      User.where('name LIKE ?', '%' + content + '%')
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
    devise_parameter_sanitizer.permit(:sign_in,keys:[:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = BookComment.new(book_comment_params)
    @book_comment.book_id = @book.id
    @book_comment.user_id = current_user.id
    unless @book_comment.save
      render 'error'  # app/views/book_comments/error.js.erbを参照する ※要件外
    end
    # app/views/book_comments/create.js.erbを参照する
  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
    # app/views/book_comments/destroy.js.erbを参照する
  end

  private
  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :book_edit_check,only: [:edit]
  def index
    @user = User.find(current_user[:id])
    logger.debug(@user.to_yaml)
    @book = Book.new
    @books = Book.all
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book.id)
    else
      @user = User.find(current_user[:id])
      @books = Book.all
      render :index
    end
  end

  def show

    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
    @new_book = Book.new
    @book_comment = BookComment.new

  end

  def edit
    @book = Book.find(params[:id])
    @user = User.find(@book.user_id)
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:notice] = "Book was successfully updated."
      redirect_to book_path(@book.id)
    else

      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to books_path
  end

   private

  def book_params
    params.require(:book).permit(:title, :body)
  end

  def book_edit_check
    @book = Book.find(params[:id])
    if @book.user != current_user
      redirect_to books_path
    end
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.new(user_id: current_user.id)
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = @book.favorites.find_by(user_id: current_user.id)
    favorite.destroy
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
  
  def about
  end

end

  

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  before_action :authenticate_user!
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end
  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end

  def followings
     user = User.find(params[:user_id])
     @users = user.followings
  end

  def followers
     user = User.find(params[:user_id])
     @users = user.followers
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!

  def search
    @model = params[:model]
		@content = params[:content]
		@method = params[:method]
		if @model == 'user'
			@records = User.search_for(@content, @method)
		else
			@records = Book.search_for(@content, @method)
		end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :user_edit_check, only: [:edit]
  def index
    @user = User.find(current_user[:id])
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @book = Book.new
  end



  def edit
    @user = User.find(params[:id])
    if @user.id != current_user.id
       redirect_to user_path(current_user)
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end
  
  def user_edit_check
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user)
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorite_helper.rb
module FavoriteHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/create.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/book_comments/destroy.js.erb
$("#book_<%= @book.id %> .comments-count").html("コメント数: <%= @book.book_comments.count %>");
$(".book_comments").html("<%= j(render 'book_comments/index', book: @book) %>");
$("#book_comment_comment").val("");

app/views/books/edit.html.erb
<% if @book.errors.any? %>
  <p><%= @book.errors.count %>errors</p>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>

      <%= form_with model:@book, local:true do |f| %>
        <p><label for="book_title">Title</label></p>
        <p><%= f.text_field :title, autofocus: true, id:"inputTitle" %></p>
        <label for="book_body">Opinion</label>
        <p><%= f.text_area :body, autofocus: true, id:"inputBody" %></p>

        <%= f.submit "Update Book" %>

        <p><%= link_to "Show", book_path(@book.id) %>
               |
           <%= link_to "Back", books_path %>
        </p>
      <% end %>

app/views/books/index.html.erb
<% if @book.errors.any? %>
  <p><%= @book.errors.count %>errors</p>
  <% @book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><h3 class="profile-name"><%= @user.name %></h3></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
          </tr>
        </tbody>
      </table>
       <div class="row">

          <p ><%= link_to "", edit_user_path(@user), class: "btn btn-outline-socondary btn-block fas fa-user-cog edit_user_27083" %></p>

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
        <p><label for="book_title">Title</label></p>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
         <p><label for="book_body">Body</label></p>
        <%= f.text_area :body, autofocus: true, id:"book_body" %>

        <%= f.submit "Create Book" %>
      <% end %>
    </div>

     <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr id="book_<%= book.id %>">
              <td><%= link_to  user_path(book.user.id) do %>
                    <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                  <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td class="favorite-btn">
                <% if book.favorited_by?(current_user) %>
                  <%= link_to book.favorites.count, book_favorites_path(book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
                <% else %>
                  <%= link_to book.favorites.count, book_favorites_path(book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
                <% end %>
              </td>
              <td class="comments-count">コメント数: <%= book.book_comments.count %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<% if flash[:notice] %>
     <p style="color:red" id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>

<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><h3 class="profile-name"><%= @user.name %></h3></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">

        <%= link_to edit_user_path(@user) do %>
            <p class="btn btn-outline-secondary btn-block fas fa-user-cog"></p>
        <% end %>

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:@new_book, local:true do |f| %>
        <p><label for="book_title">Title</label></p>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
        <p><label for="book_body">Opinion</label></p>
        <%= f.text_area :body, autofocus: true, id:"book_body" %>

        <p><%= f.submit "Create Book" %></p>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Book detail</h2>
      <table class="table table-hover table-inverse">

        <tbody>

            <tr id="book_<%= @book.id %>">
              <td>
                <%= link_to user_path(@user.id) do %>
                  <%= attachment_image_tag @book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
                <p><%= link_to @user.name, user_path(@user.id) %></p>
              </td>
              <td><%= @book.title %></td>
              <td><%= @book.body %></td>

              <td class="favorite-btn">
                <% if @book.favorited_by?(current_user) %>
                  <%= link_to @book.favorites.count, book_favorites_path(@book), method: :delete, remote: true, class: "fas fa-heart heart_red" %>
                <% else %>
                  <%= link_to @book.favorites.count, book_favorites_path(@book), method: :post, remote: true, class: "fas fa-heart heart_blue" %>
                <% end %>

              </td>
              <td class="comments-count">コメント数: <%= @book.book_comments.count %></td>

              <% if @book.user == current_user %>
              <td><%= link_to "Edit", edit_book_path(@book.id) %></td>
              <td><%= link_to "Destroy", book_path(@book.id), method: :delete, data: { confirm: '本当に削除しますか？' } %></td>
              <% end %>
            </tr>

        </tbody>
      </table>
      <div class="comments">
        <p>
        コメント件数：<%= @book.book_comments.count %></p>
        <% @book.book_comments.each do |book_comment| %>
          <p><%= image_tag('sample-author1.jpg') %></p>
          <%= book_comment.user.name %>
          <%= book_comment.created_at.strftime('%Y/%m/%d') %><%= book_comment.comment %>
          <% if book_comment.user == current_user %>
            <div class="comment-delete">
              <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
            </div>
          <% end %>
        <% end %>
      </div>
      <div class="new-comment">
        <%= form_with model:[@book,@book_comment] do |f| %>
          <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
          <%= f.submit "送信する" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/favorites/create.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/favorites/destroy.js.erb
$("#book_<%= @book.id %> .favorite-btn").html("<%= j(render 'favorites/favorite-btn', book: @book) %>");

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50,) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
  <table class='table'>
    <thead>
      <tr>
        <th>image</th>
        <th>name</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50,) %></td>
          <td><%= user.name %></td>
          <td>フォロー数: <%= user.followings.count %></td>
          <td>フォロワー数: <%= user.followers.count %></td>
          <td>
            <% if current_user != user %>
              <% if current_user.following?(user) %>
                <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete %>
              <% else %>
                <%= link_to "フォローする", user_relationships_path(user.id), method: :post %>
              <% end %>
            <% end %>
          </td>
          <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<% if @user.errors.any? %>
  <p><%= @user.errors.count %>errors</p>
  <% @user.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>

<h2>User info</h2>
<%= form_with model:@user, local:true do |f| %>
  <p><label for="inputName">Name</label></p>
  <%= f.text_field :name, autofocus: true, id:"user_name" %>

  <p><label for="inputImage">Image</label></p>
  <%= f.attachment_field :profile_image %>

  <p><label for="inputIntroduction">Introduction</label></p>
  <%= f.text_field :introduction, autofocus: true, id:"user_introduction" %>

  <p><%= f.submit "Update User" %></p>
<% end %>

app/views/users/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><h3 class="profile-name"><%= @user.name %></h3></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
          </tr>
        </tbody>
      </table>

      <div class="row">
        <% if @user.id == current_user.id %>
          <p><%= link_to "", edit_user_path(@user), class: "btn btn-outline-socondary btn-block fas fa-user-cog edit_user_27083" %></p>
        <% end %>
      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
      　<p>
        <label for="book_title">Title</label>
        </p>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
        <p>
        <label for="book_body">Opinion</label>
        </p>
        <%= f.text_area :body, autofocus: true, id:"book_body" %>

        <%= f.submit "Create Book" %>
      <% end %>

    </div>
    <div class="col-md-8 offset-md-1">
      <h2>Users</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th>image</th>
            <th>name</th>
            <th></th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= attachment_image_tag user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %></td>
              <td><%= user.name %></td>
              <td>
                <% if current_user.following?(user) %>
                  <%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, class: "btn btn-primary" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success" %>
                <% end %>
              </td>
              <td><%= link_to "Show", user_path(user) %></td>

            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% if flash[:notice] %>
     <p style="color:red" id="notice">
       <%= flash[:notice] %>
     </p>
<% end %>


<div class="container px-5 px-sm-0">
  <div class="row">
    <div class="col-md-3">
      <h2>User info</h2>
      <%= attachment_image_tag @user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
      <table class="table">
        <tbody>
          <tr></tr>
          <tr>
          <th>name</th>
          <th><h3 class="profile-name"><%= @user.name %></h3></th>
          </tr>
          <tr>
            <th>introduction</th>
            <th><%= @user.introduction %></th>
          </tr>
          <tr>
            <th>follows</th>
            <th><%= link_to @user.followings.count, user_followings_path(@user) %></th>
          </tr>
          <tr>
            <th>followers</th>
            <th><%= link_to @user.followers.count, user_followers_path(@user) %></th>
          </tr>
          <tr>
            <th>
              <% if @user.id != current_user.id %>
                <% if current_user.following?(@user) %>
                  <%= link_to "フォロー外す", user_relationships_path(@user.id), method: :delete, class: "btn btn-primary" %>
                <% else %>
                  <%= link_to "フォローする", user_relationships_path(@user.id), method: :post, class: "btn btn-success" %>
                <% end %>
              <% end %>

            </th>
          </tr>
        </tbody>
      </table>

      <div class="row">

          <p><%= link_to "", edit_user_path(@user), class: "btn btn-outline-socondary btn-block fas fa-user-cog edit_user_27083" %></p>

      </div>
      <h2 class="mt-3">New book</h2>
      <%= form_with model:@book, local:true do |f| %>
        <p>
        <label for="book_title">Title</label>
        </p>
        <%= f.text_field :title, autofocus: true, id:"book_title" %>
        <p>
        <label for="book_body">Opinion</label>
        </p>
        <%= f.text_area :body, autofocus: true, id:"book_body" %>

        <%= f.submit "Create Book" %>
      <% end %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Books</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>Title</th>
            <th>Opinion</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <% @books.each do |book| %>
            <tr>
              <td>
                <%= link_to  user_path(book.user.id) do %>
                  <%= attachment_image_tag book.user, :profile_image, :fill, 100, 100, format: 'jpeg', fallback: "no_image.jpg" %>
                <% end %>
              </td>
              <td><%= link_to book.title, book_path(book.id) %></td>
              <td><%= book.body %></td>
              <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>